### ISSUE TITLE
Local hitsound (/hitsound 2) priority is lower than intended

### ISSUE THREAD

**Issue by gyunderscorebe** [ActionFPS/ActionFPS-Game#121] opened 2017-02-04 19:57 UTC
# Bug

## Expected behavior

With `/hitsound 2` hitsound priority is SP_HIGHEST, [as intended](https://github.com/ActionFPS/ActionFPS-Game/blob/7d660426c9f93ed962b102701b7b81694cf1c105/source/src/weapon.cpp#L407).

## Actual behavior

`sound` command doesn't accept priority argument, so the priority becomes default (SP_NORMAL), which may result in more hitsounds getting dropped.

## Steps to reproduce behavior

1. Compile the game with `ACDEBUG=yes`.
2. Run the game with `/hitsound 2` and `/audiodebug 1`.
3. Hit a bot or a player.
4. Grep the log for `n = 47` (hitsound sound index), see that priority is always 1 and not 3.

**Comment by ScalaWilliam** [comment] 2017-02-04 21:06
Don't rush into coding, make sure everyone agrees that they understand what the issue is. ;)

**Comment by gyunderscorebe** [comment] 2017-02-04 21:48
Noted for future, I was just porting an existing commit =)

**Comment by ScalaWilliam** [comment] 2017-02-04 21:52
Got it. Do you have a reference to it by any chance? Always good to know the context of where things come from.

**Comment by gyunderscorebe** [comment] 2017-02-04 22:37
Uh, do you mean the commit? There isn't much context to it, I just cherry-picked it from here: assaultcube/AC#164

**Comment by ScalaWilliam** [comment] 2017-02-05 12:04
Part of #112. So closing as PR represents this issue now.

**Closed by ScalaWilliam** 2017-02-05 12:04 UTC
Labels: low-priority, postponed
